// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLEZTtRZEUZ4LhFsc-SCCw9WPsZ88BCDE',
    appId: '1:525505042435:web:e44e4c31d13c83d8ff5636',
    messagingSenderId: '525505042435',
    projectId: 'hibrwwaraq-e329e',
    authDomain: 'hibrwwaraq-e329e.firebaseapp.com',
    storageBucket: 'hibrwwaraq-e329e.firebasestorage.app',
    measurementId: 'G-WVF6C0Q69W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL3x9urtUfVD0qt7aFll69BoSPvXGIimU',
    appId: '1:525505042435:android:036b4de5466171bbff5636',
    messagingSenderId: '525505042435',
    projectId: 'hibrwwaraq-e329e',
    storageBucket: 'hibrwwaraq-e329e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6nKL1l3GGo1Rlve8CRLutTnsPG88qUE',
    appId: '1:525505042435:ios:ab68f995ee077b71ff5636',
    messagingSenderId: '525505042435',
    projectId: 'hibrwwaraq-e329e',
    storageBucket: 'hibrwwaraq-e329e.firebasestorage.app',
    iosBundleId: 'com.example.libraryMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6nKL1l3GGo1Rlve8CRLutTnsPG88qUE',
    appId: '1:525505042435:ios:ab68f995ee077b71ff5636',
    messagingSenderId: '525505042435',
    projectId: 'hibrwwaraq-e329e',
    storageBucket: 'hibrwwaraq-e329e.firebasestorage.app',
    iosBundleId: 'com.example.libraryMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLEZTtRZEUZ4LhFsc-SCCw9WPsZ88BCDE',
    appId: '1:525505042435:web:6f74aa9fffd55fbaff5636',
    messagingSenderId: '525505042435',
    projectId: 'hibrwwaraq-e329e',
    authDomain: 'hibrwwaraq-e329e.firebaseapp.com',
    storageBucket: 'hibrwwaraq-e329e.firebasestorage.app',
    measurementId: 'G-M6X0CCCX80',
  );
}
